version: '3.1'

services:
  postgres:
    image: postgres:latest
    container_name: Postgresql
    environment:
      POSTGRES_DB: ${DB_USER}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - ${DB_PORT}:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: